### ISSUE TITLE
System Error

### ISSUE THREAD

**Issue by servusdei2018** [IronLynx/maze4d#3]
When I run it from the Release, I get a `System Error`:

![unknown](https://user-images.githubusercontent.com/37554478/103162029-be77aa00-47b8-11eb-8bb1-b905ce6a8cd4.png)

**Comment by IronLynx** [comment]
Hi. Try to install [Visual C++ Redistributable for Visual Studio 2015](https://www.microsoft.com/en-ca/download/details.aspx?id=48145).

**Comment by servusdei2018** [comment]
Thank you, that fixed it!
